// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYev1SWZTL1XFWmf8Bfb4n53lgPeTdhJQ',
    appId: '1:883507365124:web:26e121b1181e442eb2fc51',
    messagingSenderId: '883507365124',
    projectId: 'safeguard-home-ai',
    authDomain: 'safeguard-home-ai.firebaseapp.com',
    storageBucket: 'safeguard-home-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2QO8wPkqIdDh8B3uY5rChv13ajNIims',
    appId: '1:883507365124:android:3582960bd8db7b5bb2fc51',
    messagingSenderId: '883507365124',
    projectId: 'safeguard-home-ai',
    storageBucket: 'safeguard-home-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTp9ZCGUg_zt280kbzKNXOyD4aUjPC1U',
    appId: '1:883507365124:ios:5ce6ea7392d70066b2fc51',
    messagingSenderId: '883507365124',
    projectId: 'safeguard-home-ai',
    storageBucket: 'safeguard-home-ai.appspot.com',
    iosBundleId: 'com.example.safeguardHomeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyTp9ZCGUg_zt280kbzKNXOyD4aUjPC1U',
    appId: '1:883507365124:ios:400cc3cd2beaea5fb2fc51',
    messagingSenderId: '883507365124',
    projectId: 'safeguard-home-ai',
    storageBucket: 'safeguard-home-ai.appspot.com',
    iosBundleId: 'com.example.safeguardHomeAi.RunnerTests',
  );
}
